### ISSUE TITLE
module is crashing in companion verison 3.3.x and 3.4.x

### ISSUE THREAD

**Issue by phwecker** [bitfocus/companion-module-shure-mxa910#3]
did some upgrade attempt to 3.3.0, 3.3.1 and 3.4.beta ... in all versions, the module only reports "crashing". works fine in 3.2.2

**Comment by phwecker** [comment]
further investigation revealed only existing instances coming from pre-3.3.x versions crash. newly created seem to work fine. 

trace logs : 
debug: Only recent lines are shown here, nothing is persisted
system: ** Starting Connection from "/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js" **
system: ** Connection started **
Starting up module class: 
Sentry disabled
Module-host accepted registration
error: Failed to init: Error: h.updatedFeedbacks is not iterable TypeError: h.updatedFeedbacks is not iterable
    at t.runThroughUpgradeScripts (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:370264)
    at /Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:374275
    at /Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:343996
    at t.default._tryToStartAnother (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:343043)
    at /Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:344203
    at new Promise (<anonymous>)
    at t.default.add (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:343846)
    at t.InstanceBase._handleInit (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:373879)
    at t.IpcWrapper.receivedMessage (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:357712)
    at process.<anonymous> (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:373363)
system: ** Connection stopped **
system: ** Starting Connection from "/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js" **
system: ** Connection started **
Starting up module class: 
Sentry disabled
Module-host accepted registration
error: Failed to init: Error: h.updatedFeedbacks is not iterable TypeError: h.updatedFeedbacks is not iterable
    at t.runThroughUpgradeScripts (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:370264)
    at /Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:374275
    at /Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:343996
    at t.default._tryToStartAnother (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:343043)
    at /Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:344203
    at new Promise (<anonymous>)
    at t.default.add (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:343846)
    at t.InstanceBase._handleInit (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:373879)
    at t.IpcWrapper.receivedMessage (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:357712)
    at process.<anonymous> (/Applications/Companion-3-3-1.app/Contents/Resources/bundled-modules/shure-mxa910/main.js:1:373363)
system: ** Connection stopped **

**Comment by dnmeid** [comment]
Thanks for the report. Fixed in a85371a20b15e5cdbc67b3cc1dfffbeb10ed0f47
